### ISSUE TITLE
error module "QtQuick" version 2.11 is not installed (but it's installed)

### ISSUE THREAD

**Issue by ghost** [MarianArlt/sddm-sugar-light#5]
So I just installed a SDDM theme on my Debian 9 and it threw
```
error module "QtQuick" version 2.11 is not installed
```
I've installed `qt5-default` via my package manager and also installed `qml` and `qml-module-qtquick-controls`
That didn't fix the issue so I removed it (kept `qtchooser`), installed _qt5.11.3_ from source with _Desktop gcc 64-bit_, setting it up with `qtchooser` and setting the variable `QT_SELECT` in my .bashrc and current terminal.

But I still got the same error.
I never used Qt or any of it's modules/APIs so I'm not sure how else I can install and setup Qt and QtQuick to get my SDDM theme to work.
Could somebody point me in the right direction?

**Comment by kushalchordiya216** [comment]
Did you manage to find a solution to this problem, im currently facing the same issue, SDDM works on breeze but not with any other theme

**Comment by waliddoch** [comment]
> So I just installed a SDDM theme on my Debian 9 and it threw
> 
> ```
> error module "QtQuick" version 2.11 is not installed
> ```
> 
> I've installed `qt5-default` via my package manager and also installed `qml` and `qml-module-qtquick-controls`
> That didn't fix the issue so I removed it (kept `qtchooser`), installed _qt5.11.3_ from source with _Desktop gcc 64-bit_, setting it up with `qtchooser` and setting the variable `QT_SELECT` in my .bashrc and current terminal.
> 
> But I still got the same error.
> I never used Qt or any of it's modules/APIs so I'm not sure how else I can install and setup Qt and QtQuick to get my SDDM theme to work.
> Could somebody point me in the right direction?

@ghost @kushalchordiya216 Have you resolved this issue?

**Comment by rajatgupta1998** [comment]
Yes I have the same issue on Kubuntu 18.04. Just joining here for updates..

**Comment by MarianArlt** [comment]
I have found several comments about this now. I find this weird.

- Could you guys please check the **Qt version for your distro**?
   This should be at least 5.11
   One way to check this would be in System Settings -> System Information -> Qt Version for those who use KDE
   Another even faster one to issue this from a cli: `qmake --version`

I use several Qt modules in these themes, but the actual error you mention is specifically about QtQuick, which is a dependency for SDDM anyways..._you can not install SDDM without QtQuick_...weird.

I also see that Debian Buster marks **libqt5quick5** and **qml-module-qtquick2** (**SDDM dependencies**) with version 5.11.3-4 which should be fine...

Make sure to have this installed on Debian (this is the optional dependency I mention in the README):
- **qml-module-qtquick-controls2** (Try only this one first)
- qml-module-qtquick-controls (Also install this one if the above doesn't work)

It also calls my attention that @kushalchordiya216 mentions that this happens with any theme?! Do you refer to any theme from @MarianArlt or just _any_ theme that is not breeze?
Could anybody confirm this? That would mean it's upstream.

Qt versioning is a freaking mess. They're trying to even this out since a few releases but there's still inconsistencies. Apparently more so with distros using outdated versions and programs written for these versions.

**Comment by rajatgupta1998** [comment]
@MarianArlt , the issue happens with all themes (any theme which is not "breeze"). 
I reinstalled the latest Kubuntu 18.04 version.

Default version for Kubuntu 18.04 is
`QMake version 3.1
Using Qt version 5.9.5`

Perhaps I should try updating qt and all of the dependencies? Sorry, might have skipped the README somehow, I will let you know if there's any progress with it. Also, agreed, the versioning is a mess. 

Anyways, thanks for responding :+1:

**Comment by MarianArlt** [comment]
Oooooh. You're on 18 LTS?
Although I find it funny that other themes are broken too. I specifically chose to support this more recent version of Qt because of some modules and recent changes.
But in all honesty I don't think most themes even care about that, and even some themes require Qt versions way older than 5.9 as far as I know.

I would _strongly_ advise against partially upgrading system components like Qt above what your distro released for your release version.
You might choose to leave 18 behind though and update your whole OS. Kubuntu's latest long term support is 20.04

Would appreciate the others confirming that this is indeed a version mismatch with their OS before closing.

**Comment by rajatgupta1998** [comment]
Thanks again for the support @MarianArlt . I think I understood the issue here. However, will stick to 18.04 as of now. Thank you :)
